SRC_TRG_TXT_DIC = {
    # Human face
    'tanned': (['face'],
               ['tanned face']),
    'pale': (['face'],
             ['pale face']),
    'makeup': (['person'],
               ['person with makeup']),
    'no_makeup': (['person'],
                  ['person without makeup']),
    'old': (['person'],
            ['old person']),
    'young': (['person'],
              ['young person']),
    'beards': (['person'],
               ['person with beards']),
    'angry': (['face'],
              ['angry face']),
    'surprised': (['face'],
                  ['surprised face']),
    'smiling': (['face'],
                ['smiling face']),
    'blond_hair': (['person'],
                   ['person with blond hair']),
    'red_hair': (['person'],
                 ['person with red hair']),
    'grey_hair': (['person'],
                  ['person with red hair']),
    'curly_hair': (['person'],
                   ['person with curly hair']),

    'nicolas': (['Person'],
                ['Nicolas Cage']),
    'zuckerberg': (['Person'],
                   ['Mark Zuckerberg']),
    'benedict': (['Person'],
              ['Benedict Cumberbatch']),
    'gogh': (['photo'],
             ['painting by Gogh']),
    'frida': (['photo'],
              ['self-portrait by Frida Kahlo']),
    'modigliani': (['photo'],
                   ['Painting in Modigliani style']),
    'sketch': (['photo'],
              ['sketch']),
    'watercolor': (['photo'],
                   ['Watercolor Art with Thick Brushstrokes']),
    'elf': (['Human'],
            ['Tolkien elf']),
    'super_saiyan': (['Human'],
                     ['Super saiyan']),
    'pixar': (['Human'],
              ['3D render in the style of Pixar']),
    'neanderthal': (['Human'],
                    ['Neanderthal']),
    'zombie': (['Human'],
               ['Zombie']),
    'jocker': (['Human'],
               ['The Jocker']),


    # Dog face
    'dog_nicolas': (['Dog'],
                    ['Nicolas Cage']),
    'dog_yorkshire': (['Dog'],
                      ['Yorkshire Terrier']),
    'dog_smiling': (['Dog'],
                    ['Smiling Dog']),
    'dog_zombie': (['Dog'],
                   ['Zombie']),
    'dog_super_saiyan': (['Dog'],
                         ['Super saiyan']),
    'dog_venom': (['Dog'],
                  ['Venom']),
    'dog_bear': (['Dog'],
                 ['Bear']),
    'dog_fox': (['Dog'],
                ['Fox']),
    'dog_wolf': (['Dog'],
                 ['Wolf']),
    'dog_hamster': (['Dog'],
                    ['Hamster']),


    # Church
    'church_snow': (['Church'],
                    ['Snow Coverd Church']),
    'church_night': (['Church'],
                     ['Church at night']),
    'church_red_brick': (['Church'],
                         ['Red brick wall Church']),
    'church_golden': (['Church'],
                      ['Golden Church']),
    'church_wooden_house': (['Church'],
                            ['Wooden House']),
    'church_gothic': (['Church'],
                      ['Gothic Church']),
    'church_ancient_tower': (['Church'],
                             ['Ancient traditional Asian tower']),
    'church_temple': (['Church'],
                      ['Temple']),
    'church_factory': (['church'],
                       ['factory with chimneys']),
    'church_department_store': (['church'],
                                ['department store']),


    # Bedroom
    'bedroom_blue': (['Bedroom'],
                     ['Blue tone Bedroom']),
    'bedroom_green': (['Bedroom'],
                      ['Green tone Bedroom']),
    'bedroom_golden': (['Bedroom'],
                       ['Golden Bedroom']),
    'bedroom_princess': (['Bedroom'],
                         ['Princess Bedroom']),
    'bedroom_palace': (['Bedroom'],
                       ['Palace Bedroom']),
    'bedroom_wooden': (['Bedroom'],
                       ['Wooden Bedroom']),


}